CREATE DATABASE  IF NOT EXISTS `mfa_service` 
USE `mfa_service`;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `MFA_OTP`
--

DROP TABLE IF EXISTS `MFA_OTP`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `MFA_OTP` (
  `CHANNEL` varchar(20) NOT NULL,
  `CATEGORY` varchar(20) NOT NULL,
  `TOKEN_ID` varchar(50) NOT NULL,
  `OTP_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `OTP_CODE` varchar(6) NOT NULL,
  `TYPE` varchar(1) NOT NULL,
  `STATUS` varchar(1) NOT NULL,
  `CREATE_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATE_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`CHANNEL`,`CATEGORY`,`TOKEN_ID`,`OTP_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `MFA_TOKEN`
--

DROP TABLE IF EXISTS `MFA_TOKEN`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `MFA_TOKEN` (
  `CHANNEL` varchar(20) NOT NULL,
  `CATEGORY` varchar(20) NOT NULL,
  `TOKEN_ID` varchar(50) NOT NULL,
  `STATUS` varchar(1) NOT NULL,
  `CREATE_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATE_DT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`CHANNEL`,`CATEGORY`,`TOKEN_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
